window.PRODUCTS = [
  {
    id: 1,
    title: "One Piece Vol.1",
    price: 5.99,
    oldPrice: 0,
    category: "Shonen",
    img: "/gambarManga/OnePiece.png",
    author: "Eiichiro Oda",
    publisher: "Shueisha",
    volume: 1,
    description:
      "Monkey D. Luffy, a cheerful boy with a rubber body, sets sail from his small village to find the legendary treasure known as One Piece and become the Pirate King. Along the way he befriends skilled and unusual crewmates and faces dangerous foes on the high seas. Volume 1 introduces Luffy's dream, his unpredictable spirit, and the start of an epic adventure.",
  },
  {
    id: 2,
    title: "Naruto Vol.2",
    price: 4.99,
    oldPrice: 0,
    category: "Shonen",
    img: "/gambarManga/Naruto.png",
    author: "Masashi Kishimoto",
    publisher: "Shueisha",
    volume: 2,
    description:
      "Naruto Uzumaki continues his journey from mischievous outcast to determined ninja, training hard to prove himself to his village and achieve his dream of becoming Hokage. He faces increasingly dangerous challenges and begins to learn the meaning of friendship, courage, and responsibility.",
  },
  {
    id: 3,
    title: "Attack on Titan Vol.35",
    price: 6.99,
    oldPrice: 0,
    category: "Seinen",
    img: "/gambarManga/AttackOnTitan.png",
    author: "Hajime Isayama",
    publisher: "Kodansha",
    volume: 1,
    description:
      "After humanity is nearly wiped out by giant man-eating Titans, Eren Yeager vows vengeance and joins the Scout Regiment to fight back. The story explores fear, sacrifice, and the desperate struggle to reclaim a world lost to monstrous invaders.",
  },
  {
    id: 4,
    title: "Sailor Moon Vol.1",
    price: 5.49,
    oldPrice: 0,
    category: "Shoujo",
    img: "/gambarManga/SailorMoon.png",
    author: "Naoko Takeuchi",
    publisher: "Kodansha",
    volume: 1,
    description:
      "Usagi Tsukino discovers she is Sailor Moon, a magical guardian destined to protect Earth and search for a legendary princess. With newfound friends and powers, she must face dark forces while learning the value of friendship, love, and courage.",
  },
  {
    id: 5,
    title: "Berserk Vol.1",
    price: 7.99,
    oldPrice: 0,
    category: "Seinen",
    img: "/gambarManga/Beserk.png",
    author: "Kentaro Miura",
    publisher: "Hakusensha",
    volume: 1,
    description:
      "Guts, a mercenary with a tragic past and unmatched swordsmanship, wanders a brutal medieval world haunted by demons and betrayal. This volume introduces his fierce will to survive, the heavy cost of revenge, and the grim realities of a world ruled by darkness.",
  },
  {
    id: 6,
    title: "My Hero Academia Vigilante",
    price: 7.99,
    oldPrice: 0,
    category: "Shonen",
    img: "/gambarManga/Vigilantes.png",
    author: "Kohei Horikoshi",
    publisher: "Shueisha",
    volume: 1,
    description:
      "Izuku Midoriya, born without powers in a world of superheroes, inherits a legendary Quirk and enrolls in U.A. High School to become the next great hero. Vol.1 follows his first trials, friendships, and the hard work it takes to stand for justice.",
  },
  {
    id: 7,
    title: "Kimi ni Todoke Vol.1",
    price: 4.99,
    oldPrice: 0,
    category: "Shoujo",
    img: "/gambarManga/KiminiTodoke.png",
    author: "Karuho Shiina",
    publisher: "Shueisha",
    volume: 1,
    description:
      "Sawako Kuronuma, misunderstood because of her gloomy appearance, slowly learns to connect with classmates and form deep friendships. This gentle, emotional volume explores first love, trust, and the ways people can change each other's lives.",
  },
  {
    id: 8,
    title: "Demon Slayer Vol.23",
    price: 6.49,
    oldPrice: 0,
    category: "Shonen",
    img: "/gambarManga/Kimetsu.png",
    author: "Koyoharu Gotouge",
    publisher: "Shueisha",
    volume: 1,
    description:
      "After his family is slain by demons and his sister turned into one, Tanjiro Kamado sets out to train as a demon slayer and find a way to cure her. The story blends heartbreaking stakes, intense training, and determined heroism.",
  },
  {
    id: 9,
    title: "Vagabond Vol.23",
    price: 6.99,
    oldPrice: 0,
    category: "Seinen",
    img: "/gambarManga/Vagabound.png",
    author: "Takehiko Inoue",
    publisher: "Kodansha",
    volume: 1,
    description:
      "A fictionalized account of the early life of swordsman Miyamoto Musashi, following his search for strength and purpose through brutal duels and self-reflection. Vol.1 captures the raw energy of a young warrior learning the meaning of victory and honor.",
  },
  {
    id: 10,
    title: "Haikyuu!! Vol.1",
    price: 5.49,
    oldPrice: 0,
    category: "Shonen",
    img: "/gambarManga/Haikyuu.png",
    author: "Haruichi Furudate",
    publisher: "Shueisha",
    volume: 1,
    description:
      "Shoyo Hinata’s obsession with volleyball leads him to challenge bigger, more skilled opponents and to join a high school team determined to rise from underdogs to champions. This energetic volume focuses on teamwork, rivalry, and the thrill of sport.",
  },
  {
    id: 11,
    title: "Nana Vol.2",
    price: 6.99,
    oldPrice: 0,
    category: "Seinen",
    img: "/gambarManga/Nana.png",
    author: "Ai Yazawa",
    publisher: "Shueisha",
    volume: 1,
    description:
      "Two women who share the same name, Nana, meet by chance and form a complicated friendship as they chase their dreams in Tokyo—one pursuing love and relationships, the other aiming for success in music. Vol.1 sets the stage for a story about ambition, heartbreak, and the bonds that tie people together.",
  },
  {
    id: 12,
    title: "Fruits Basket Vol.2",
    price: 5.99,
    oldPrice: 0,
    category: "Shoujo",
    img: "/gambarManga/Fruits Basket.png",
    author: "Natsuki Takaya",
    publisher: "Hakusensha",
    volume: 1,
    description:
      "Tohru Honda, a kind-hearted high school girl, becomes entwined with a mysterious family cursed to transform into animals of the Chinese zodiac. This touching volume explores healing, acceptance, and the quiet power of compassion in the face of strange burdens.",
  },
];
